# Generated by Django 2.2.3 on 2019-07-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0035_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
